
spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
  security:
    oauth2:
      resourceserver: 
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/microservice-realm    
server:
  port: 8076

test:
  name: Configration flashed!

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
