
spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service
      
server:
  port: 8076

test:
  name: Abhishek

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/